### ISSUE TITLE
Simplify client API?

### ISSUE THREAD

**Issue by Burwin** [JarrodJ83/LowKey#2]
You've probably gone back and forth on this, and your examples are likely showing the stock API in order to be as clear as possible.

That said, have you thought about shortening the path to some common tasks? For example, rather than this:
```
// SINGLE TENANT
config.AddStore(new DataStore(DataStores.Sql, sqlDatabase), sqlServer).WithSqlServer(sqlConnBuilder);

// MULTI-TENANT
var tenantResolver = new QueryStringTenantResolver(new Tenant(sqlServer, sqlServer));
config.AddStore(new DataStore(DataStores.SqlMultiTenant, sqlDatabase), 
    tenantResolverFactory: () => tenantResolver,
    tenantIdResolverFactory: () => tenantResolver).WithSqlServer(sqlConnBuilder);
```

You do this, instead?
```
// SINGLE TENANT
config.AddSqlServerStore(DataStores.Sql, sqlDatabase, sqlServer, sqlConnBuilder);

// MULTI-TENANT
var tenantResolver = new QueryStringTenantResolver(new Tenant(sqlServer, sqlServer));
config.AddSqlServerStore(DataStores.SqlMultiTenant, sqlDatabase, sqlConnBuilder, 
    tenantResolverFactory: () => tenantResolver,
    tenantIdResolverFactory: () => tenantResolver);
```

Maybe it doesn't matter that much, actually, because it's done just a couple times in the application setup and never again, and because these proposals didn't shorten it very much, and because it's less explicit now. Whatever, something to think about if you're bored.

**Comment by JarrodJ83** [comment]
Appreciate the feedback/suggestion! The `AddStore` is provided by the hosting package but then the `WithSqlServer` is provided by the SQL implementation. Surprisingly (or maybe not) it's challenging to come up with a good fluent API for configuring things so I welcome the suggestion. I think my basic premise was that I wanted it to be as easy as possible for someone to add a new type of client so the `WithSqlServer` literally just registers the SqlServer implementations it needs. If I did `AddSqlServerStore` then every client implementation would also have to know how to register the data store in their extension methods as well so I think that is why I kept them separate. Given that, do you think it would still be worth trying to consolidate?
